# Generated by Django 3.1.5 on 2021-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistic',
            name='volume',
        ),
        migrations.AddField(
            model_name='logistic',
            name='item_des',
            field=models.TextField(default=' package content is a Box... ', max_length=225, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='mode',
            field=models.CharField(default='Air', max_length=50, verbose_name='Mode of transit'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='trackId',
            field=models.CharField(default='856AE3B03A', max_length=20, primary_key=True, serialize=False),
        ),
    ]
