# Generated by Django 3.1.5 on 2021-02-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210207_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='logistic',
            name='trackId',
            field=models.CharField(default='4AB32B1DE7', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BillClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_dis', models.TextField(max_length=225, verbose_name='Bill Description')),
                ('Amount', models.CharField(max_length=50, verbose_name='Total Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.paymentaccount', verbose_name='Choose Pay Account')),
                ('logistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.logistic', verbose_name='client')),
            ],
        ),
    ]
